In [3]:
import torch
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [4]:
print(torch.__version__)

2.1.0+cu121


In [6]:
# Introduction to Tensors

In [8]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [9]:
scaler.ndim

0

In [10]:
scaler.item()

7

In [11]:
# Vector

vector = torch.tensor([1,7])

In [12]:
vector

tensor([1, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [15]:
# Matrix

MATRIX = torch.tensor([[7,8],[10,10]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# Tensor

In [21]:
TENSOR = torch.tensor([[[1,1,1],[2,2,2],[3,3,3]]])

In [25]:
TENSOR.ndim


3

In [26]:
TENSOR.shape

torch.Size([1, 3, 3])

In [28]:
# # Random Tensors

# why random tensors:

# Random tensors are inportant because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data'

# start with random numbers -> look at data -> update random numbers -> look at data -> update

In [38]:
random_tensor = torch.rand(size =(3,4,5))
random_tensor

tensor([[[0.7474, 0.7242, 0.6277, 0.9423, 0.7161],
         [0.0253, 0.9123, 0.1784, 0.4494, 0.8574],
         [0.1421, 0.7781, 0.6765, 0.2780, 0.8090],
         [0.6600, 0.7954, 0.3352, 0.0288, 0.5917]],

        [[0.4218, 0.8804, 0.5923, 0.6079, 0.1435],
         [0.3783, 0.1252, 0.7961, 0.2542, 0.0249],
         [0.5831, 0.2005, 0.2255, 0.5408, 0.3368],
         [0.3771, 0.9285, 0.6679, 0.2934, 0.2663]],

        [[0.5898, 0.8748, 0.9870, 0.3907, 0.1624],
         [0.4089, 0.9701, 0.4178, 0.4222, 0.6782],
         [0.4362, 0.2768, 0.1584, 0.9960, 0.1090],
         [0.0372, 0.2268, 0.2701, 0.2000, 0.2579]]])

In [41]:
random_tensor.ndim


3

In [43]:
# Create a random tesnor with similar shape to an image

random_image_size_tensor = torch.rand(size = (224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [44]:
# Creating Tensors with zeros and ones

In [50]:
zero = torch.zeros(size =(224,224,3))
zero

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [51]:
zero * random_image_size_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [54]:
ones = torch.ones(size = (2,2))

In [56]:
ones.ndim

2

In [57]:
# Creating Tensor range and tensors like another tensor

In [64]:
one_to_ten = torch.arange(start=1, end =1000, step =99)

In [65]:
one_to_ten

tensor([  1, 100, 199, 298, 397, 496, 595, 694, 793, 892, 991])

In [67]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [66]:
# Creating tensors like

ten_zeros = torch.zeros_like(input = one_to_ten)

In [68]:
# Dealing with tensor data types

In [77]:
float32_tensor = torch.tensor([3,6,7], dtype = None,
                              device = 'cuda',
                              requires_grad = False
                              )

In [78]:
float32_tensor.dtype


torch.int64

In [79]:
float_16_tensor = float32_tensor.type(torch.float16)

In [80]:
float_16_tensor.dtype

torch.float16

In [81]:
float32_tensor * float_16_tensor

tensor([ 9., 36., 49.], device='cuda:0', dtype=torch.float16)

In [82]:
# Getting Tensor Attributes

In [85]:
int32_tensor = torch.tensor([3,5,7], dtype = torch.int32)
int32_tensor

tensor([3, 5, 7], dtype=torch.int32)

In [87]:
int32_tensor

tensor([3, 5, 7], dtype=torch.int32)

In [88]:
# Getting Information from tensor

int32_tensor.dtype

torch.int32

In [89]:
int32_tensor.shape

torch.Size([3])

In [90]:
int32_tensor.device

device(type='cpu')

In [95]:
print('data type of Tensor={}'.format(int32_tensor.dtype))

data type of Tensor=torch.int32


In [96]:
# Manipulating Tensors

In [97]:
# 1. Addition
# 2. Subtraction
# 3. Multiplication
# 4. Division
# 5.Matrix Multiplication

In [99]:
tensor_a = torch.tensor([1,2,3])
tensor_a + 10

tensor([11, 12, 13])

In [100]:
tensor_a = torch.tensor([1,2,3])
tensor_a *  10

tensor([10, 20, 30])

In [102]:
torch.mul(tensor_a, 10)

tensor([10, 20, 30])

In [103]:
tensor_a * tensor_a

tensor([1, 4, 9])

In [105]:
torch.matmul(tensor_a, tensor_a)

tensor(14)

In [107]:
# Matrix Multiplication by hand

In [108]:
%%time
torch.matmul(tensor_a, tensor_a)

CPU times: user 556 µs, sys: 6 µs, total: 562 µs
Wall time: 485 µs


tensor(14)

In [109]:
tensor_a = torch.tensor([[1,2],[3,4],[5,6]])

In [117]:
tensor_a.shape


torch.Size([3, 2])

In [121]:
tensor_b = torch.tensor([[1,2],[3,4],[5,6]])
tensor_b.shape

torch.Size([3, 2])

In [127]:
tensor_b = tensor_b.T

In [131]:
tensor_b = tensor_b.reshape(shape =(2,3))


In [132]:
torch.matmul(tensor_a, tensor_b)

tensor([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])

In [133]:
# Finding min, max, mean and sum of Tensor Aggregation

In [143]:
torch.mean(tensor_a.type(torch.float32))

tensor(3.5000)

In [144]:
# Find the positional min and max of tensors

In [145]:
tensor_a.argmin()

tensor(0)

In [147]:
tensor_a.argmax()

tensor(5)

In [148]:
# Reshaping, viewing and stacking tensors

In [154]:
tensor_a.reshape(shape = (2,3,1))

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])

In [150]:
tensor_a.shape

torch.Size([3, 2])

In [155]:
# Change the view

In [156]:
z = tensor_a.view(1,6)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6]]), torch.Size([1, 6]))

In [159]:
z = tensor_a.view(1,6)

In [161]:
z == tensor_a

tensor([[True, True],
        [True, True],
        [True, True]])

In [162]:
# Stack Tensors on top of each other

In [168]:
tensor_a_stacked = torch.stack([tensor_a,tensor_a,tensor_a,tensor_a], dim=0)

In [169]:
tensor_a_stacked

tensor([[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]])

In [170]:
# Squezzing, unsquezzing and permuting tensors

In [177]:
torch.unsqueeze(tensor_a, dim=0)

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [180]:
x = torch.randn(2,3,5)
x.size()

torch.permute(x, (2,0,1)).size()

torch.Size([5, 2, 3])

In [181]:
X_original = torch.randn(size =(224,224,3))

In [182]:
X_original

tensor([[[ 1.0737, -1.5447,  2.2001],
         [-0.3277,  0.9254, -0.0220],
         [ 1.0071,  2.9336, -0.3487],
         ...,
         [ 0.7084, -0.3948, -0.1302],
         [ 1.0882,  0.2639,  0.6447],
         [-0.4045,  1.4234, -0.1257]],

        [[ 0.9469, -1.2466,  0.5357],
         [-0.1690,  0.1734,  0.9816],
         [ 0.6505,  1.0289, -0.4936],
         ...,
         [-2.3960,  0.8059,  0.4194],
         [-0.2217, -2.4616, -0.9614],
         [-1.1061, -0.5018, -0.3760]],

        [[ 2.0156,  2.8049,  0.0344],
         [ 0.5210, -0.3934, -0.6056],
         [-0.9780,  0.2496,  0.0234],
         ...,
         [-1.2960,  2.0503,  0.7608],
         [ 0.5526, -1.5351, -0.6803],
         [-0.5024, -0.5772,  0.4262]],

        ...,

        [[-0.1193, -1.0197, -2.0384],
         [-0.2191,  0.2255, -0.0031],
         [-0.2994, -0.8131, -0.1283],
         ...,
         [-1.0573,  0.6044,  0.4545],
         [-0.6942, -1.9804, -0.9232],
         [ 0.6365,  1.6102, -0.3453]],

        [[

In [184]:
X_permuted = X_original.permute(2,0,1)

In [185]:
X_permuted.shape

torch.Size([3, 224, 224])

In [186]:
X_original.shape

torch.Size([224, 224, 3])

In [187]:
# Selecting data from tensors

In [188]:
# Indexing (selecting data from tensors)

# Indexing in tesnors in similar like array in numpy

In [191]:
x = torch.arange(1,10).reshape(1,3,3)

In [192]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [193]:
# lets index

In [197]:
x[:][0][0]

tensor([1, 2, 3])

In [198]:
# get index from 0th abd 1st dimension and all values of 2nd dimension

In [202]:
x[0][2][2]

tensor(9)

In [226]:
x[:,:,2]

tensor([[3, 6, 9]])

In [228]:
# Pytorch Reproducbility


In [233]:
torch.rand(2,2)
torch.manual_seed(42
                  )

In [234]:
# Acessing gpu in pytorch

In [235]:
import torch
torch.cuda.is_available()

True

In [237]:
# Setup device agnostic code

In [238]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [239]:
device

'cuda'

In [240]:
torch.cuda.device_count()

1

In [241]:
# Exercies

In [249]:
rand = torch.rand(size = (7,7   ))
rand.shape

torch.Size([7, 7])

In [251]:
rand2 = torch.rand(size = (1,7   )).reshape(7,1)
rand2.shape

torch.Size([7, 1])

In [252]:
torch.matmul(rand, rand2)

tensor([[1.5815],
        [1.4061],
        [1.0741],
        [1.6700],
        [1.8314],
        [1.3191],
        [1.0933]])